defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

seed: 4

data:
  batch_size: 128

env:
  act_dim: 10
  seq_len: 100
  bandit_type: mean
  train_len: 200

model:
  n_head: 4
  lr: 1e-4
  weight_decay: 1e-4
  warmup_fraction: 0.1
  hidden_dim: 128
  layer_norm_epsilon: 1e-5
  max_position_embeddings: 1024
  embd_pdrop: 0.1
  resid_pdrop: 0.1
  attn_pdrop: 0.1
  num_layers: 4

  act_dim: ${env.act_dim}
  seq_len: ${env.seq_len}

train:
  eval_interval: 100
  epsilon: 0.5
  num_epochs: 1000
  wandb: false
