name: dream
hp_name: dream_bt-${env.bandit_type}_s-${seed}

defaults:
  - base
  - override model: dream_model
  - override env: bandit
  - _self_

# Checkpoint settings
save_every: 1000  # Save checkpoint every N epochs
load_from_ckpt: null  # Path to checkpoint dir to load from, or null

# DQN specific settings
exploit_policy:
  type: learned
  learning_rate: 0.0001
  initial_epsilon: 1.0
  test_epsilon: 0.0
  buffer:
    type: sequential
    buffer_size: 16000
    sequence_length: 50
  min_buffer_size: 500
  batch_size: 32
  update_freq: 4
  target_update_freq: 5000
  max_grad_norm: 10
  gamma: 0.99
  state_embedder_factory: ${model.instruction_embedder}

exploration_policy:
  type: learned
  learning_rate: 0.0001
  initial_epsilon: 1.0
  test_epsilon: 0.0
  buffer:
    type: sequential
    buffer_size: 16000
    sequence_length: 50
  min_buffer_size: 8000
  batch_size: 32
  update_freq: 4
  target_update_freq: 5000
  max_grad_norm: 10
  gamma: 0.99
  state_embedder_factory: ${model.exploration_embedder} 