name: fete 
hp_name: ${name}-${env.hp_name}_s-${seed}

update_behavior_every: 50 # in terms of episodes
num_episodes: ${env.num_episodes}
weighting: false

weighting: True
temperature: 1.0  # For training
eval_temperature: 10.0  # For evaluation

defaults:
  - base
  - override model: fete_gpt2
  - override env: bandit
  - _self_

model:
  env:
    timesteps_per_episode: ${env.timesteps_per_episode}
    obs_dim: ${env.obs_dim}
    act_dim: ${env.act_dim}